commands = [
  { savefile_manager = "ctrl+o" },
  { item_spawner = "ctrl+u" },
  { character_stats = true },
  { warp = true },
  { cycle_speed = [1.0, 3.0, 6.0], hotkey = "8" },
  { runes = 10000, hotkey = "9" },
  { group = "Position storage", commands = [
    { nudge = 1.0, nudge_up = "[", nudge_down = "]" },
    { position = "h", save = "rshift+h" },
    { position = "j", save = "rshift+j" },
    { position = "k", save = "rshift+k" },
  ]},
  { group = "Render flags", commands = [
    { flag = "show_map", hotkey = "f4" },
    { flag = "show_chr", hotkey = "f5" },
    { flag = "display_stable_pos", hotkey = "f6" },
    { flag = "hitbox_high", hotkey = "f7" },
    { flag = "hitbox_low", hotkey = "f8" },
    { flag = "hitbox_f" },
    { flag = "hitbox_character" },
    { flags = ["weapon_hitbox1", "weapon_hitbox2", "weapon_hitbox3"], hotkey = "f9", label = "Weapon hitboxes" },
  ]},

  { flag = "no_damage", hotkey = "1" },
  { flag = "no_stamina_consume", hotkey = "2" },
  { flags = ["no_fp_consume", "no_ashes_of_war_fp_consume"], hotkey = "3", label = "Inf Focus" },
  { flags = ["no_goods_consume", "no_arrows_consume"], hotkey = "4", label = "Inf Consumables" },
  { flag = "deathcam", hotkey = "5" },
  { flag = "no_dead", hotkey = "6" },
  { flag = "one_shot", hotkey = "7" },
  { target = "ctrl+n" },
  { flag = "no_update_ai", hotkey = "f1" },
  { flag = "gravity", hotkey = "f2" },
  { flag = "torrent_gravity", hotkey = "f2" },
  { flags = ["collision", "torrent_collision"], label = "No Collision" },
  { flag = "action_freeze", hotkey = "ctrl+l" },

  { quitout = "p" },

  # These flags are currently broken for some reason. TODO investigate.
  # { flags = ["field_area_direction", "field_area_altimeter" , "field_area_compass"], hotkey = "9", label = "Field area HUD" },
]

[settings]
log_level = "INFO"
display = "0"
hide = "rshift+0"
dxgi_debug = false
show_console = false
indicators = [
  { indicator = "game_version", enabled = true },
  { indicator = "igt", enabled = true },
  { indicator = "position", enabled = false },
  { indicator = "fps", enabled = false },
  { indicator = "framecount", enabled = false },
  { indicator = "imgui_debug", enabled = false }
]